# apiVersion: v1
# kind: Service
# metadata:
#   name: team-two-webapp-clusterip
#   namespace: team-two-webapp
# spec:
#   selector:
#     app: team-two-webapp
#   ports:
#     - port: 80
#       targetPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: team-two-webapp-loadbalancer
  namespace: team-two-webapp
spec:
  type: LoadBalancer
  selector:
    app: team-two-webapp
  ports:
    - port: 80
      targetPort: 8080

